---
kind: pipeline
name: lib

platform:
  os: linux
  arch: amd64

steps:
- name: version
  image: syncloud/build-deps-amd64
  commands:
  - "echo $DRONE_BUILD_NUMBER > version"

- name: test
  image: syncloud/build-deps-amd64
  commands:
  - pip install -e .
  - py.test

- name: deploy
  image: syncloud/build-deps-amd64
  commands:
  - ./upload.sh
  environment:
    PYPI_LOGIN:
      from_secret: PYPI_LOGIN
    PYPI_PASSWORD:
      from_secret: PYPI_PASSWORD

...
