platform: linux/amd64

clone:
  git:
    image: syncloud/drone-git-amd64
    depth: 50

pipeline:
  version:
    image: syncloud/build-deps-amd64
    commands:
      - echo $DRONE_BUILD_NUMBER > version
      
  test:
    image: syncloud/build-deps-amd64
    commands:
      - pip install -e .
      - py.test
  
  deploy:
    image: syncloud/build-deps-amd64
    #secrets: [PYPI_USER, PYPI_PASSWORD]
    commands:
      #- python setup.py register -r https://www.python.org/pypi
      - python setup.py sdist upload -r https://$PYPI_USER:$PYPI_PASSWORD@www.python.org/pypi
    