language: python
env:
  matrix:
  - DEVTOOLS_REPO=https://raw.githubusercontent.com/syncloud/dev-tools/master
  global:
    secure: xmceSumNef9meYhv0ntIq6CaQ1ZXixDKb0u0ifaQZvBmMDzrnbHxafyvTMMXwbs0zw+B4cZYv2RYyhx/+cMMGxiw45BVm1djYO5LilPPB/O7wknfRexNYHKm+dUoJZvzDgopfz7+YTZtKlI245XVgUpRCTrpL/PSqMeHf0Bh6Hn+nwhNUbr/oXDaeWSI2PaWjACvbT4ovt2iYoUf1h2U5+HA72i9AQyNe1dTMFdsx9HHQpqIZDiUGDaxTn4fyrrCITHAFsIKzHqdu/WYM+6ye1wHvRSJ4DD4ISd1HQSUy0JDu9fHoxlSXzWMYF7Kz1+6PWg2l8agU/Dt1HDisGfI+Zo13czXVG81gD9sej41ldnLyPuJ+CRWlZD5V7x1ddsTtZXEFIEHH+qFBuxAQ8NeOhWFDefvvKxOGmuUbk3nPfSJO9uluTrKvuf+eTo1vJFhLatFPMrbYwGEv2iNKX2DuQUfZ9pSstVzAVsJLL/0no0TBsNuPtbtQGiK/cqAjE9xUwBzjWEH9TVt3C2TK9qAV87kAhvlZNhLTdSQU4AtmfI8W3n0DDE+Tjvxc5iQa/0ozAXxRwUrkxoN6KawSSAWoaPo3N8JAt82NDLlLg66myoxniXnoKJKdywn3W1JBj9unkwKrtSPtl2PWF3M7l0/KfTnqk51zu3pYQFvi48nw40=
install:
- pip install -e .
script:
- py.test
deploy:
  provider: pypi
  user: syncloud-build
  password:
    secure: Z96OHDAgtdm/rcvYdXg7zYgnsBfdcAo9QYpWcvO2fvTc4fCfoj8ZYEw+STVmP2ryQk6W7is0qn3Svh+5/YzWh324DUD/2OK1slOgBvtMv/IYFssMdDOUeOnz7WUMIoS2K7SI0C0MsCdieUUmhhju076t+WM4ELngW4eYmmiHxyYCfkXCklFTUCdT4xgS5t81IUmtVK3bEh5FZD/qEzwIO8VPgmq/be63vngceTYmJFLF4hAjNZGgh6tPZfK7WOvrmCD1/FE4AeOkS67GxuCfo+InbsloNFMps8vnPI9YpGIWUqcT/1a6iE9qVLS/aFyQCZxC9S28IckUqe/L5VxCG/S31tYqGheoEFnXC2LQlIjF7EeagmDxUgqxmhTIYHPui+CX3yEZlQN+7ZhY7h7lBuDSUy3zBy7FOsmInIykA8SgutJ/N7qd836DydhTvZMbMuQX/Ic3rcHNn8ealjlIsG82Vep4krNnVmeuxG/nAfxGSG+YQq3c7nMXjPi58GUlc7J82i22zHNoEHOOzHsSwUihkp/VPQ8a2iMqV08ewBlRX3EOaWzkj88iYhMvjsglNzzrhBrRjcjoOPZDyTtxKHy2mkLx1DSb6Sq9udoVKqhOIhQvEpFwQlDBYZemwnKMd2hNQYV1csmthaEbtQtv4AzQWTpHQNR+TfNzBXdYcE8=
after_deploy:
- wget ${DEVTOOLS_REPO}/version-increment
- chmod +x version-increment
- wget ${DEVTOOLS_REPO}/version-push
- chmod +x version-push
- ./version-increment version
- ./version-push version ${TRAVIS_REPO_SLUG} syncloud-build GH_TOKEN ${TRAVIS_BRANCH} "Travis build [skip ci]"
