language: python
env:
  global:
    secure: Dj7I+HVIVVpg+vtXbqN0ka0ZRgzTblQr1C/67TfTfkFJN6KFYA3vPJS7ZSbewBzL3odHpKFfJT6tu5Mhe7afxd1JXX+V2KpzbyveNL6fJzm6YiNHueBDR/oRfBBny+09E3U2pTBNxvtHBH0SQYG+QL723e3T6npjeTllKIc/0Pd/kxxOYwYIb0ictrf5P9OegrvNt2r+yvj7zHSVQ2OPkFeIO+yOINHJkwlgCGrdRQRDOpLT66q2OFGcElWAngBG1dF196G21oSZmFFkok8iBBKNitkHSeXMLmRpxy2Hyy1QvPDiVwbtFiwKwHygkZLa5zCIux0bCkxDaXCX6w5aCQzT+mvLkImI3R9VTMxYwnoFCtfD6pzf4GqisiV0j3K2C7g5T9VZX5CusYgAkioWwYzwwp+EkuJfl+9xuk3Au1ubdTkhUholL6LZssy6qt1u4i3uZxi8We1MntPYcMp/NPljmzaoFEohFQV+THAB1e1HXi2knps9brEE/ipSbDYO8wXmLXBcpxu24DeCpJLhe1KmB16uaxE7XdjF3lZ2Z+hBYvhv+8LZxGz+8JYe3fsYZYMBt9UTz1sRTcL8/sl1NRSL8WAUmXnc5ygrVM3vW7r8+gxlauMW8DNeYaMSPin8dpI6+51Ueentk3A5NT+PUxWkeQ2FSisxZVJdjSXdTN0=
install:
- pip install -e .
script:
- py.test
deploy:
  provider: pypi
  user: syncloud-build
  password:
    secure: Z96OHDAgtdm/rcvYdXg7zYgnsBfdcAo9QYpWcvO2fvTc4fCfoj8ZYEw+STVmP2ryQk6W7is0qn3Svh+5/YzWh324DUD/2OK1slOgBvtMv/IYFssMdDOUeOnz7WUMIoS2K7SI0C0MsCdieUUmhhju076t+WM4ELngW4eYmmiHxyYCfkXCklFTUCdT4xgS5t81IUmtVK3bEh5FZD/qEzwIO8VPgmq/be63vngceTYmJFLF4hAjNZGgh6tPZfK7WOvrmCD1/FE4AeOkS67GxuCfo+InbsloNFMps8vnPI9YpGIWUqcT/1a6iE9qVLS/aFyQCZxC9S28IckUqe/L5VxCG/S31tYqGheoEFnXC2LQlIjF7EeagmDxUgqxmhTIYHPui+CX3yEZlQN+7ZhY7h7lBuDSUy3zBy7FOsmInIykA8SgutJ/N7qd836DydhTvZMbMuQX/Ic3rcHNn8ealjlIsG82Vep4krNnVmeuxG/nAfxGSG+YQq3c7nMXjPi58GUlc7J82i22zHNoEHOOzHsSwUihkp/VPQ8a2iMqV08ewBlRX3EOaWzkj88iYhMvjsglNzzrhBrRjcjoOPZDyTtxKHy2mkLx1DSb6Sq9udoVKqhOIhQvEpFwQlDBYZemwnKMd2hNQYV1csmthaEbtQtv4AzQWTpHQNR+TfNzBXdYcE8=
env:
- DEVTOOLS_REPO=https://raw.githubusercontent.com/syncloud/dev-tools/master
after_deploy:
- wget ${DEVTOOLS_REPO}/version-increment
- chmod +x version-increment
- wget ${DEVTOOLS_REPO}/version-push
- chmod +x version-push
- "./version-increment version"
- ./version-push version ${TRAVIS_REPO_SLUG} syncloud-build GH_TOKEN ${TRAVIS_BRANCH}
  "Travis build [skip ci]"
